### ISSUE TITLE
possible emojis

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [NikSavchenk0/rbxcustom-fontemojis#7]
https://github.com/linusg/serenityos-emoji-font
https://github.com/c1710/blobmoji

**Comment by NikSavchenk0** [comment]
> https://github.com/linusg/serenityos-emoji-font https://github.com/c1710/blobmoji

Blobmoji have sizes 128x128, Twemoji by Mozilla is 100x100.
SerenityOSEmoji is not showing emojis.
